# Generated by Django 5.2.6 on 2025-11-19 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appLiher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='identificacion',
            options={'managed': True, 'verbose_name': 'Datos de Identificación', 'verbose_name_plural': 'Datos de Identificación'},
        ),
        migrations.AlterModelOptions(
            name='permiso',
            options={'managed': True},
        ),
    ]
