# Generated by Django 5.2.6 on 2025-11-21 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLiher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('iddevolucion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('proceso', 'En Proceso'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('evidencia', models.ImageField(blank=True, null=True, upload_to='devoluciones/')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_rechazo', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('pedido', models.ForeignKey(db_column='idpedido', on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='appLiher.pedidos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'devoluciones',
            },
        ),
        migrations.CreateModel(
            name='DevolucionItem',
            fields=[
                ('iditem', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('monto_item', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='appLiher.devolucion')),
                ('producto', models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.CASCADE, to='appLiher.producto')),
                ('variante', models.ForeignKey(db_column='idvariante', on_delete=django.db.models.deletion.CASCADE, to='appLiher.varianteproducto')),
            ],
            options={
                'db_table': 'devoluciones_items',
            },
        ),
    ]
