# Generated by Django 5.2.6 on 2025-11-20 02:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLiher', '0002_alter_catalogo_options_alter_identificacion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('tipo_direccion', models.CharField(choices=[('Calle', 'Calle'), ('Carrera', 'Carrera'), ('Avenida', 'Avenida'), ('Transversal', 'Transversal'), ('Diagonal', 'Diagonal'), ('Circular', 'Circular')], max_length=50)),
                ('calle', models.CharField(max_length=10)),
                ('letra', models.CharField(blank=True, max_length=5)),
                ('numero', models.CharField(max_length=10)),
                ('adicional', models.CharField(blank=True, max_length=10)),
                ('barrio', models.CharField(max_length=100)),
                ('piso_apartamento', models.CharField(blank=True, max_length=100)),
                ('direccion_completa', models.CharField(blank=True, max_length=255)),
                ('nombre_receptor', models.CharField(max_length=100)),
                ('telefono_receptor', models.CharField(blank=True, max_length=20)),
                ('empresa_envio', models.CharField(choices=[('coordinadora', 'Coordinadora'), ('interrapidisimo', 'Interrapidísimo'), ('envia', 'Transportadora Envia')], max_length=50)),
                ('costo_envio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
                'db_table': 'envios_detallados',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Envios',
        ),
        migrations.RemoveField(
            model_name='identificacion',
            name='field_documento',
        ),
        migrations.AddField(
            model_name='identificacion',
            name='acepta_terminos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='identificacion',
            name='autoriza_datos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='identificacion',
            name='autoriza_publicidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='identificacion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='identificacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='identificacion',
            name='numero_documento',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='identificacion',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='identificacion',
            name='celular',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='identificacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='identificacion',
            name='tipo_documento',
            field=models.CharField(choices=[('DNI', 'DNI'), ('Pasaporte', 'Pasaporte'), ('Tarjeta de identidad', 'Tarjeta de identidad'), ('Cedula de ciudadania', 'Cédula de ciudadanía'), ('Cedula de extranjeria', 'Cédula de extranjería')], max_length=50),
        ),
        migrations.AddField(
            model_name='envio',
            name='identificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='appLiher.identificacion'),
        ),
        migrations.AddField(
            model_name='envio',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envios', to=settings.AUTH_USER_MODEL),
        ),
    ]
