# Generated by Django 5.2.6 on 2025-09-30 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLiher', '0002_agregar_catalogo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='producto',
        ),
        migrations.AlterField(
            model_name='inventario',
            name='catalogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='appLiher.catalogo'),
        ),
    ]
