# Generated by Django 5.2.6 on 2025-09-30 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appLiher', '0003_remove_inventario_producto_alter_inventario_catalogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='stock',
        ),
    ]
