# Generated by Django 5.2.6 on 2025-11-27 05:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLiher', '0003_envio_delete_envios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envios',
            fields=[
                ('idenvios', models.AutoField(primary_key=True, serialize=False)),
                ('departamentos', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('tipo_direccion', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=50)),
                ('letra', models.CharField(max_length=50)),
                ('numero', models.BigIntegerField()),
                ('barrio', models.CharField(max_length=50)),
                ('piso', models.CharField(max_length=50)),
                ('nombre_receptor', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'envios',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='catalogo',
        ),
        migrations.RemoveField(
            model_name='entradainventario',
            name='idinventario_fk',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='identificacion',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='color',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='talla',
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Color', 'verbose_name_plural': 'Colores'},
        ),
        migrations.AlterModelOptions(
            name='identificacion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='permiso',
            options={},
        ),
        migrations.AlterModelOptions(
            name='talla',
            options={'verbose_name': 'Talla', 'verbose_name_plural': 'Tallas'},
        ),
        migrations.RemoveField(
            model_name='permiso',
            name='catalogo',
        ),
        migrations.AddField(
            model_name='categoria',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='color',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='talla',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='talla',
            name='talla',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('referencia', models.CharField(max_length=10, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('imagen', models.ImageField(blank=True, max_length=255, null=True, upload_to='productos/')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appLiher.categoria')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('idvariante', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, max_length=255, null=True, upload_to='productos/variantes/')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appLiher.color')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='appLiher.producto')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appLiher.talla')),
            ],
            options={
                'db_table': 'variante_producto',
                'unique_together': {('producto', 'talla', 'color')},
            },
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appLiher.varianteproducto', verbose_name='Variante del Producto'),
        ),
        migrations.AlterField(
            model_name='peticionproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appLiher.varianteproducto'),
        ),
        migrations.DeleteModel(
            name='Catalogo',
        ),
        migrations.DeleteModel(
            name='EntradaInventario',
        ),
        migrations.DeleteModel(
            name='Envio',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
