# Generated by Django 5.2.6 on 2025-09-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLiher', '0004_remove_inventario_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
