# Generated by Django 5.2.6 on 2025-10-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLiher', '0005_inventario_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='nombre',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
