# Generated by Django 5.2.6 on 2025-10-01 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appLiher', '0006_remove_usuarios_nombre_usuarios_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='address',
        ),
    ]
