# Generated by Django 5.2.6 on 2025-10-21 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLiher', '0007_remove_usuarios_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeticionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.PositiveIntegerField(default=1)),
                ('fecha_peticion', models.DateTimeField(auto_now_add=True)),
                ('atendida', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appLiher.inventario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Petición de Producto',
                'verbose_name_plural': 'Peticiones de Productos',
                'db_table': 'peticiones_producto',
                'managed': True,
            },
        ),
    ]
